### ISSUE TITLE
can you  provide raw data

### ISSUE THREAD

**Issue by johnjiangok** [ESkripichnikov/market-making#1]
PATH_TO_FILE = 'md/btcusdt:Binance:LinearPerpetual/'
can you provide raw data to download?  thank you

**Comment by EvaGalois** [comment]
I used your data processing, and I only got 55 feature data, but you processed 57 data. It seems I still need you to provide some data. . . . Or you can make the readme richer. I changed your code and it stuck with bugs for many days.
can you provide raw data to download? thank you.
I hope to know all 57 fields of features, and the fields corresponding to the 57 elements of stds means.

**Comment by ESkripichnikov** [comment]
> PATH_TO_FILE = 'md/btcusdt:Binance:LinearPerpetual/' can you provide raw data to download? thank you

I apologize, but the raw data is not publicly available as it's private to this project. Therefore, I'm unable to share the raw data for download. However, if you have any specific questions about how to work with this data or need further information regarding its usage, please don't hesitate to ask.
