### ISSUE TITLE
Can you explain the meaning of the parameters of the action space?

### ISSUE THREAD

**Issue by EvaGalois** [ESkripichnikov/market-making#4]
I want to know what the significance is of setting 1, 5, and 10.
|ActionID|1|2|3|4|5|6|7|8|9|0|
|-|-|-|-|-|-|-|-|-|-|-|
|Ask|1|1|1|5|5|5|10|10|10|/|
|Bid|1|5|10|1|5|10|1|5|10|/|

**Comment by ESkripichnikov** [comment]
When I selected the potential actions, I aimed to encompass a broad spectrum of actions, including symmetrical and asymmetrical, close and wide quoting. Therefore, I simply opted for 1, 5, and 10 to illustrate this point. In reality, you have the flexibility to choose any other bid/ask levels and corresponding actions.
